spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/masscommercialcity
    username: lq
    password: lq980918
    #指定数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置，以下配置不能自动生效，因为在DataSourceproperties中并没有与之对应的信息
    ## 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
 #禁用模板引擎缓存
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
logging:
  level:
    com.four.masscommercialcity: debug
#用于扫描mybaits xml配置的属性文件
#mybatis:
#  config-location: classpath: xxx/xx.xml
#  mapper-locations: classpath: xxx/xx/*.xml
    #springboot2.0以后的版本 必须加上以下配置 才能生效
#    initialization-mode: always
#    schema:
#      - classpath:sql/meeting1.sql